blank_issues_enabled: false
contact_links:
  - name: Dev Instructions
    url: https://github.com/NullDev/tldr-extension?tab=readme-ov-file#wrench-building-yourself-dev-only
    about: Click this link to view the dev instructions.
